version: '3.8'

services:

  db:
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile_db
    environment:
#      POSTGRES_DB: kanalservis
#      POSTGRES_USER: kanal_user
#      POSTGRES_PASSWORD: strongpassword_vhf494
       POSTGRES_HOST_AUTH_METHOD: trust
    container_name: db
    ports:
      - "54321:5432"

  django_proj:
    container_name: kanalservis
    restart: always
    build: .
#    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
       - db
#  bot:
#    restart: always
#    build: .

#    links:
#       - db:db
#    networks:
#       - network1
#networks:
#  network1:
#    driver: bridge

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"


