# Generated by Django 4.0.6 on 2022-07-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('price_usd', models.FloatField(blank=True, null=True)),
                ('price_rub', models.FloatField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
