# Generated by Django 4.0.6 on 2022-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
