# Generated by Django 4.0.6 on 2022-07-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='error_message',
        ),
    ]
