# Generated by Django 4.0.6 on 2022-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_order_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('notifications', models.BooleanField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Заказ №'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_rub',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость, Р'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость, $'),
        ),
    ]
